### ISSUE TITLE
Problems about Segmentation fault

### ISSUE THREAD

**Issue by henryhaotian** [miccol/ROS-Behavior-Tree#15] opened 2017-11-09 02:27 UTC
Hi @miccol ,I was new in ROS and BT.
When i installed ,i checked the installation by the example:
`$ roslaunch behavior_tree_leaves test_behavior_tree.launch`
The result was:
`[ INFO] [1510192545.521117587]: Waiting For the Acutator named action to start`
`[ INFO] [1510192545.897654005]: The Acutator action has started`
`[ INFO] [1510192546.030964858]: Waiting For the Acutator named condition to start`
`[ INFO] [1510192546.239948285]: Actuator condition Started`
`Start Drawing!`
`Segmentation fault (core dumped)`
So i read the code and thought the problem may occured due to DotBt. Then i Commented-Out:
`// BT::DotBt dotbt(root);`
`//std::thread t(&BT::DotBt::publish, dotbt);`
And recompile. The result was:
`[ INFO] [1510193675.814797855]: Waiting For the Acutator named action to start`
`[ INFO] [1510193676.030049476]: The Acutator action has started`
`[ INFO] [1510193676.132046947]: Waiting For the Acutator named condition to start`
`[ INFO] [1510193676.336096227]: Actuator condition Started`
`Start Drawing!`
`Ticking the root node !`
`[ INFO] [1510193676.336497677]: I am running the request`
`action is setting its status to 3`
`seq1NEEDS TO TICK action`
`action is setting its status to 3`
`[ INFO] [1510193676.338210673]: I am running the request to action`
`action is setting its status to 0`
`action is setting its status to 0`
`action is setting its status to 0`
`action is setting its status to 0`
`action is setting its status to 0`
`Segmentation fault (core dumped)`
I read your code for few days. It maybe the problem of Library, but i don't know how to sovle it.

**Comment by miccol** [comment] 2017-11-09 07:36
Hi Henry,

I just re-installed and launched the code. Seems to be fine.

```
 michele@michele-3558:~/catkin_ws$ roslaunch behavior_tree_leaves test_behavior_tree.launch 
... logging to /home/michele/.ros/log/f4b6da20-c51e-11e7-bb9b-c304c0a0e8c1/roslaunch-michele-3558-5377.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://michele-3558:33759/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    action (behavior_tree_leaves/action_example)
    condition (behavior_tree_leaves/condition_example)
    test (behavior_tree_core/gtest_ros)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[action-1]: started with pid [5395]
process[condition-2]: started with pid [5396]
process[test-3]: started with pid [5397]
```

So let's work together to figure out what problem causes your segfault. 
We can start checking your rosdistro, rosversion, and linux distro version.
Does the window with the drawing of the BT appear?

Michele

**Comment by henryhaotian** [comment] 2017-11-10 03:11
Hi~
My linux distro was Ubuntu 14.04 lts, kernel was:
```
henry@henry-m5510:~$ uname -a
Linux henry-m5510 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
I launched the code, the result was:
```
henry@henry-m5510:~$ roslaunch behavior_tree_leaves test_behavior_tree.launch 
... logging to /home/henry/.ros/log/a9e32cca-c5b8-11e7-9289-e4a7a06d5e89/roslaunch-henry-m5510-3645.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://henry-m5510:43834/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    action (behavior_tree_leaves/action_example)
    condition (behavior_tree_leaves/condition_example)
    test (behavior_tree_core/gtest_ros)

auto-starting new master
process[master]: started with pid [3657]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to a9e32cca-c5b8-11e7-9289-e4a7a06d5e89
process[rosout-1]: started with pid [3670]
started core service [/rosout]
process[action-2]: started with pid [3673]
process[condition-3]: started with pid [3674]
process[test-4]: started with pid [3705]
[test-4] process has died [pid 3705, exit code -11, cmd /home/henry/catkin_ws/devel/lib/behavior_tree_core/gtest_ros __name:=test __log:=/home/henry/.ros/log/a9e32cca-c5b8-11e7-9289-e4a7a06d5e89/test-4.log].
log file: /home/henry/.ros/log/a9e32cca-c5b8-11e7-9289-e4a7a06d5e89/test-4*.log
```
And there was no drawing of the BT.
I read the code, and the program came segfault when it execute `std::this_thread::sleep_for(std::chrono::milliseconds(10));` at line 52 in sequence_node.cpp
Then i Commented-Out:
`\\BT::DotBt dotbt(root);` at line 27 in behavior_tree.cpp
`\\std::thread t(&BT::DotBt::publish, dotbt);` at line 28 in behavior_tree.cpp
`\\std::this_thread::sleep_for(std::chrono::milliseconds(10));` at line 52 in sequence_node.cpp
And i used the Terminator rosrun the code respectly:
`roscore`
`rosrun behavior_tree_core gtest_ros`
`rosrun behavior_tree_leaves condition_example`
`rosrun behavior_tree_leaves action_example`
So the condition_example result was:
```
[ INFO] [1510282730.584182259]:  Enum: 0
[ INFO] [1510282730.584211977]:  condition Ready for Ticks
[ INFO] [1510282730.594556498]: Condition Server Started
[ INFO] [1510282735.259028256]: Condition /condition Succeeded
```
the action_example result was:
```
[ INFO] [1510282726.550063115]:  Enum: 0
[ INFO] [1510282726.550166426]:  Action Ready for Ticks
[ INFO] [1510282735.260410955]: Starting Action
[ INFO] [1510282735.260498850]: Executing Action
[ INFO] [1510282735.760797683]: Executing Action
[ INFO] [1510282736.261123379]: Executing Action
[ INFO] [1510282736.761405428]: Executing Action
[ INFO] [1510282737.261682509]: Executing Action
[ INFO] [1510282737.761951406]: Action /action Succeeded
```
the gtest_ros result was:
```
[ INFO] [1510282734.745444772]: Waiting For the Acutator named action to start
[ INFO] [1510282734.952500008]: The Acutator action has started
[ INFO] [1510282734.990443989]: Waiting For the Acutator named condition to start
[ INFO] [1510282735.257515847]: Actuator condition Started
Start Drawing!
Ticking the root node !
[ INFO] [1510282735.257920689]: I am running the request
action is setting its status to 3
seq1NEEDS TO TICK action
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
action is setting its status to 3
seq1 is HALTING children from 2
seq1 is setting its status to 0
[ INFO] [1510282735.259720726]: I am running the request to action
action is setting its status to 0
action is setting its status to 0
action is setting its status to 0
...
(so many "action is setting its status to 0")
...
action is setting its status to 0
action is setting its status to 0
action is setting its status to 0
Segmentation fault (core dumped)
```
So the program of gtest_ros came segfault during the action_example's statue was RUNNING. It could not get the signal of SUCCESS after few seconds.
I thought the reason may be the mutex at line 42-50 in tree_node.cpp. 
Hope to receive your reply！

Henry

**Comment by miccol** [comment] 2017-11-10 07:41
I don't think the problem is in the sleep. I would have the same problem. The problem could be in your openGL library. Try to comment the following in behavior_tree.cpp https://github.com/miccol/ROS-Behavior-Tree/blob/4287572b0ae379b9ffcf915b08c385c00a184198/behavior_tree_core/src/behavior_tree.cpp#L24-L27

**Comment by henryhaotian** [comment] 2017-11-13 02:38
Hi @miccol 
You are right,the problem was the openGL library.
I used the laptop which has Nvidia Graphics card and Intel Graphics card.
When i switch the Intel Graphics card and roslaunch the  program, it worked.
When i turn to Nvidia Graphics card it occured segmentation fault.
Is it the result i use the **open source NVIDIA driver** ?  When i installed the **official NVIDIA driver** the laptop could not work.
So do you use Nvidia Graphics card and open source NVIDIA driver ?
Hope to receive your reply！

Henry

**Comment by miccol** [comment] 2017-11-13 09:11
I have the official NVIDIA Drivers, probably you have some compatibility issue. 
Closing the issue as it is not a problem of the repository, but we can continue the discussion.

**Closed as completed by miccol** 2017-11-13 09:11 UTC
